montoTotal=int(input("Ingrese el monto total de las piezas"))
if montoTotal>500000:
    dineroPropioEmpresa=float(montoTotal*0.55)
    prestamoBanco=float(montoTotal*0.3)
    prestamoFabricante=float(montoTotal*0.15)
    interes=float(prestamoFabricante*0.2)
    deudaFabricante=float(prestamoFabricante+interes)
    print ("El monto total es de : ", montoTotal)
    print ("El dinero perteneciente de la Empresa es de : ", dineroPropioEmpresa)
    print ("El prestamo de banco es de : ", prestamoBanco)
    print ("El prestamo del fabricante es de : ", prestamoFabricante)
    print ("El interes de prestamo es de : ", interes)
    print ("La deuda total del fabricante es de : ", deudaFabricante)
else:
    dineroPropioEmpresa=float(montoTotal*0.7)
    prestamoBanco=float(montoTotal*0.3)
    print ("Monto total: ", montoTotal)
    print ("Dinero Propio De La Empresa: ", dineroPropioEmpresa)
    print ("Prestamo de Banco: " , prestamoBanco)